add answer as a target to logger
trevordevore/levure pull request #165
Opened 2021-04-27 18:19 UTC by macMikey

2022-07-17 20:02 UTC, trevordevore requested changes

2022-07-17 20:02 UTC, trevordevore commented on framework/helpers/logger/loggerLibrary.livecodescript
> +  else if sLogTarget is "db" then
@macMikey The "db" target needs to be removed from this PR.

2023-04-20 15:10 UTC, trevordevore commented
Never heard back about corrections that need to be made.

2023-04-20 15:10 UTC, closed without merging

2023-04-21 20:30 UTC, macMikey commented
wupz.
yeah, i should have dumped this, instead of letting it sit there. i wound up going in another direction.